# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release to NuGet

on:
  release:
    types: [published]
  
env:
  # must contain the version with v prefix
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set release version
      run: |    
        # Strip leading 'v' if present
        if [[ "$RELEASE_TAG" == v* ]]; then
          RELEASE_VERSION="${RELEASE_TAG:1}"
        else
          RELEASE_VERSION=$RELEASE_TAG
        fi
        echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

    - name: Print version
      run: |
        echo "Version: $RELEASE_VERSION"

    # Setup
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore
    - name: Restore dependencies
      run: |
        dotnet restore -v quiet
      
    # Build
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore /p:Version=$RELEASE_VERSION
      
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal
